[package]
name = "waterway-mops"
version = "3.3.4"
description = "Waterway Labs Type Library"
repository = "https://github.com/jamesbeadle/waterway-mops"
keywords = [ "motoko", "football" ]
license = "Apache-2.0"

[dependencies]
base = "0.16.0"
