[package]
name = "football-types"
version = "1.0.1"
description = "FootballTypes used in FootballGod OpenFPL OpenWSL"
repository = "https://github.com/JohnNixon6972/FootballTypes"
keywords = [ "football-types","footballgod","openfpl","openwsl" ]
license = "MIT"

[dependencies]
base = "0.13.7"