[package]
name = "waterway-mops"
version = "3.2.13"
description = "Waterway Labs Type Library"
repository = "https://github.com/jamesbeadle/waterway-mops"
keywords = [ "motoko", "football", "golf" ]
license = "Apache-2.0"

[dependencies]
base = "0.14.9"
