[package]
name = "waterway-mops"
version = "1.0.0"
description = "Types used across Waterway Labs Products"
repository = "https://github.com/jamesbeadle/waterway-mops.git"
keywords = [ "FootballTypes", "BaseTypes" ]
license = "Apache-2.0"

[dependencies]
base = "0.14.0"